// Web push: telling somebody something happened when the studio is not
// running at all — a phone in a pocket (spec/ §6, ideas/notifications.md).
// Rung 1 is the browser's own notification while a tab is alive
// (public/notify.js); this is the half that reaches a closed app.
//
// ⚠️ It is hand-rolled, and that is the one thing here `new-y` does
// differently: it takes `web-push` off npm, and this studio has no runtime
// dependency at all (`npm ci --omit=dev` is the whole install). Everything
// below is two RFCs and `node:crypto`'s webcrypto, about a hundred lines:
//
//   RFC 8292  VAPID — an ES256 JWT saying who is sending, so the push
//             service will take a message from this studio at all.
//   RFC 8291  the payload — ECDH against the browser's own key, HKDF twice,
//             AES-128-GCM. The push service carries it and cannot read it,
//             which is the point: what people here say to each other does
//             not become readable by Apple and Google on the way.
//   RFC 8188  the `aes128gcm` framing the body above is wrapped in.
//
// Both are tested against the RFCs' own worked examples (test/push.test.js),
// which is what makes a thing like this safe to hand-roll: the alternative
// would be testing against somebody's live servers.

import { webcrypto as crypto } from 'node:crypto';

const B64 = (bytes) => Buffer.from(bytes).toString('base64url');
const UNB64 = (text) => new Uint8Array(Buffer.from(text, 'base64url'));
const utf8 = (text) => new TextEncoder().encode(text);

const join = (...parts) => {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let at = 0;
  for (const part of parts) { out.set(part, at); at += part.length; }
  return out;
};

/* Keys ---------------------------------------------------------------------- */

// A VAPID pair, the shape `bin/pushkeys.js` prints and studio.env holds: the
// public key as the 65-byte uncompressed point every browser expects, the
// private one as the bare 32-byte scalar, both base64url. The same shape
// `web-push` uses, so a pair generated by either works with either.
export async function makeKeys() {
  const pair = await crypto.subtle.generateKey(
    { name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify'],
  );
  const jwk = await crypto.subtle.exportKey('jwk', pair.privateKey);
  const raw = await crypto.subtle.exportKey('raw', pair.publicKey);
  return { publicKey: B64(new Uint8Array(raw)), privateKey: jwk.d };
}

// ⚠️ The private half is a scalar and webcrypto will not import one on its
// own: a JWK needs `x` and `y` beside `d`, and they come out of the public
// key's uncompressed point — byte 0 is the 0x04 that says "uncompressed",
// then 32 bytes of x and 32 of y.
async function signingKey(publicKey, privateKey) {
  const point = UNB64(publicKey);
  if (point.length !== 65 || point[0] !== 0x04) {
    throw new Error('VAPID public key is not a 65-byte uncompressed P-256 point');
  }
  return crypto.subtle.importKey('jwk', {
    kty: 'EC',
    crv: 'P-256',
    d: privateKey,
    x: B64(point.subarray(1, 33)),
    y: B64(point.subarray(33, 65)),
    ext: true,
  }, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign']);
}

/* VAPID (RFC 8292) ---------------------------------------------------------- */

// Twelve hours. The RFC caps it at 24 and a shorter one buys nothing here:
// the token is made per send and thrown away.
const VAPID_HOURS = 12;

// The header the push service checks before it will carry anything. `aud` is
// the *origin* of the endpoint and not the endpoint — sending the whole URL
// is the mistake that gets a 401 from Firefox and a shrug from Chrome.
export async function vapidHeader(endpoint, { publicKey, privateKey, subject }) {
  const claims = {
    aud: new URL(endpoint).origin,
    exp: Math.floor(Date.now() / 1000) + VAPID_HOURS * 3600,
    sub: subject,
  };
  const signed = `${B64(utf8(JSON.stringify({ typ: 'JWT', alg: 'ES256' })))}`
    + `.${B64(utf8(JSON.stringify(claims)))}`;
  const key = await signingKey(publicKey, privateKey);
  // ⚠️ ES256 is r‖s, 64 raw bytes, which is what webcrypto returns — not the
  // DER sequence `node:crypto`'s own sign() would give. Wrapping the wrong
  // one is a signature every push service rejects.
  const signature = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' }, key, utf8(signed),
  );
  return `vapid t=${signed}.${B64(new Uint8Array(signature))}, k=${publicKey}`;
}

/* The payload (RFC 8291 over RFC 8188) -------------------------------------- */

// One record, which is all a push message ever is: 4096 is what a browser
// guarantees to accept, and what the studio sends is a couple of hundred
// bytes (`messageText` cuts the words to one line). The room left over is the
// record minus the 86-byte header, the 16-byte tag and the one-byte
// delimiter — a guard rather than a thing that happens, because a record
// bigger than `rs` is one a browser drops without saying so.
const RECORD_SIZE = 4096;
const MAX_PAYLOAD = RECORD_SIZE - 86 - 17;

const hkdf = async (ikm, salt, info, bytes) => new Uint8Array(await crypto.subtle.deriveBits(
  { name: 'HKDF', hash: 'SHA-256', salt, info },
  await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']),
  bytes * 8,
));

// Encrypt one message for one subscription. `keys` is the browser's own pair
// off the subscription — `p256dh`, its public point, and `auth`, sixteen
// bytes of secret it keeps — and the salt and ephemeral key are arguments
// only so the RFC's worked example can be replayed exactly; every real send
// leaves them alone and gets fresh ones.
export async function encrypt(plaintext, { p256dh, auth }, replay = null) {
  if (Buffer.byteLength(plaintext, 'utf8') > MAX_PAYLOAD) {
    throw new Error(`a push payload must be at most ${MAX_PAYLOAD} bytes`);
  }
  const ua = UNB64(p256dh);
  const authSecret = UNB64(auth);
  const uaKey = await crypto.subtle.importKey(
    'raw', ua, { name: 'ECDH', namedCurve: 'P-256' }, false, [],
  );
  const pair = replay?.pair ?? await crypto.subtle.generateKey(
    { name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits'],
  );
  const as = new Uint8Array(await crypto.subtle.exportKey('raw', pair.publicKey));
  const salt = replay?.salt ?? crypto.getRandomValues(new Uint8Array(16));

  // The shared secret, then the two derivations. ⚠️ The first is salted with
  // the browser's `auth` secret and the second with this message's salt —
  // swapping them is the mistake that produces a body every browser silently
  // drops, because a push that will not decrypt is not an error anybody sees.
  const shared = new Uint8Array(await crypto.subtle.deriveBits(
    { name: 'ECDH', public: uaKey }, pair.privateKey, 256,
  ));
  const ikm = await hkdf(shared, authSecret, join(utf8('WebPush: info\0'), ua, as), 32);
  const cek = await hkdf(ikm, salt, utf8('Content-Encoding: aes128gcm\0'), 16);
  const nonce = await hkdf(ikm, salt, utf8('Content-Encoding: nonce\0'), 12);

  const key = await crypto.subtle.importKey('raw', cek, 'AES-GCM', false, ['encrypt']);
  // 0x02 is the delimiter that says "last record" (RFC 8188 §2). A 0x01 here
  // means a record that is not the last, and the browser waits for one more.
  const body = join(utf8(plaintext), Uint8Array.of(0x02));
  const sealed = new Uint8Array(await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv: nonce, tagLength: 128 }, key, body,
  ));

  // The header the record sits behind: salt, record size, then the sender's
  // public key with its length in front of it (RFC 8188 §2.1).
  const size = new Uint8Array(4);
  new DataView(size.buffer).setUint32(0, RECORD_SIZE);
  return join(salt, size, Uint8Array.of(as.length), as, sealed);
}

/* Sending ------------------------------------------------------------------- */

// Read once at boot. Absent, everything below is a no-op and the studio says
// nothing about it: push is a thing you set up, not a thing that broke.
export function pushConfig(env = process.env) {
  const publicKey = env.VAPID_PUBLIC_KEY;
  const privateKey = env.VAPID_PRIVATE_KEY;
  const subject = env.VAPID_SUBJECT;
  if (!publicKey || !privateKey || !subject) return null;
  return { publicKey, privateKey, subject };
}

// Four hours. Long enough that a phone switched off overnight still hears
// about the afternoon; short enough that nobody is told about a conversation
// that has since moved on.
const TTL = 4 * 3600;

// One send. Returns the status so the caller can drop a subscription the push
// service says is gone; a network failure is a 0, the same shape the client's
// own `send()` uses.
export async function sendOne(subscription, payload, config, fetcher = fetch) {
  const body = await encrypt(payload, subscription);
  try {
    const res = await fetcher(subscription.endpoint, {
      method: 'POST',
      headers: {
        Authorization: await vapidHeader(subscription.endpoint, config),
        'Content-Encoding': 'aes128gcm',
        'Content-Type': 'application/octet-stream',
        TTL: String(TTL),
      },
      body,
    });
    return res.status;
  } catch {
    return 0;
  }
}
